### ISSUE TITLE
checkboxes and radio buttons should have focus highlight

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/sheer#7]
checkboxes and radio buttons do not display focus highlight due to following styles

``` css
select:focus,
input:focus,
button:focus {
  border: var(--default-focus-highlight-border);
  outline: none;
}
```
